INSERT INTO [dbo].[ISOcountryCode]([country], [alpha2Code], [alpha3Code]) VALUES ('Andorra', 'AD', 'AND');
INSERT INTO [dbo].[ISOcountryCode]([country], [alpha2Code], [alpha3Code]) VALUES ('United Arab Emirates', 'AE', 'ARE');
INSERT INTO [dbo].[ISOcountryCode]([country], [alpha2Code], [alpha3Code]) VALUES ('Afghanistan', 'AF', 'AFG');
INSERT INTO [dbo].[ISOcountryCode]([country], [alpha2Code], [alpha3Code]) VALUES ('Antigua and Barbuda', 'AG', 'ATG');
INSERT INTO [dbo].[ISOcountryCode]([country], [alpha2Code], [alpha3Code]) VALUES ('Anguilla', 'AI', 'AIA');
INSERT INTO [dbo].[ISOcountryCode]([country], [alpha2Code], [alpha3Code]) VALUES ('Albania', 'AL', 'ALB');
INSERT INTO [dbo].[ISOcountryCode]([country], [alpha2Code], [alpha3Code]) VALUES ('Armenia', 'AM', 'ARM');
INSERT INTO [dbo].[ISOcountryCode]([country], [alpha2Code], [alpha3Code]) VALUES ('Angola', 'AO', 'AGO');
INSERT INTO [dbo].[ISOcountryCode]([country], [alpha2Code], [alpha3Code]) VALUES ('Antarctica', 'AQ', 'ATA');
INSERT INTO [dbo].[ISOcountryCode]([country], [alpha2Code], [alpha3Code]) VALUES ('Argentina', 'AR', 'ARG');
INSERT INTO [dbo].[ISOcountryCode]([country], [alpha2Code], [alpha3Code]) VALUES ('American Samoa', 'AS', 'ASM');
INSERT INTO [dbo].[ISOcountryCode]([country], [alpha2Code], [alpha3Code]) VALUES ('Austria', 'AT', 'AUT');
INSERT INTO [dbo].[ISOcountryCode]([country], [alpha2Code], [alpha3Code]) VALUES ('Australia', 'AU', 'AUS');
INSERT INTO [dbo].[ISOcountryCode]([country], [alpha2Code], [alpha3Code]) VALUES ('Aruba', 'AW', 'ABW');
INSERT INTO [dbo].[ISOcountryCode]([country], [alpha2Code], [alpha3Code]) VALUES ('Aland Islands', 'AX', 'ALA');
INSERT INTO [dbo].[ISOcountryCode]([country], [alpha2Code], [alpha3Code]) VALUES ('Azerbaijan', 'AZ', 'AZE');
INSERT INTO [dbo].[ISOcountryCode]([country], [alpha2Code], [alpha3Code]) VALUES ('Bosnia and Herzegovina', 'BA', 'BIH');
INSERT INTO [dbo].[ISOcountryCode]([country], [alpha2Code], [alpha3Code]) VALUES ('Barbados', 'BB', 'BRB');
INSERT INTO [dbo].[ISOcountryCode]([country], [alpha2Code], [alpha3Code]) VALUES ('Bangladesh', 'BD', 'BGD');
INSERT INTO [dbo].[ISOcountryCode]([country], [alpha2Code], [alpha3Code]) VALUES ('Belgium', 'BE', 'BEL');
INSERT INTO [dbo].[ISOcountryCode]([country], [alpha2Code], [alpha3Code]) VALUES ('Burkina Faso', 'BF', 'BFA');
INSERT INTO [dbo].[ISOcountryCode]([country], [alpha2Code], [alpha3Code]) VALUES ('Bulgaria', 'BG', 'BGR');
INSERT INTO [dbo].[ISOcountryCode]([country], [alpha2Code], [alpha3Code]) VALUES ('Bahrain', 'BH', 'BHR');
INSERT INTO [dbo].[ISOcountryCode]([country], [alpha2Code], [alpha3Code]) VALUES ('Burundi', 'BI', 'BDI');
INSERT INTO [dbo].[ISOcountryCode]([country], [alpha2Code], [alpha3Code]) VALUES ('Benin', 'BJ', 'BEN');
INSERT INTO [dbo].[ISOcountryCode]([country], [alpha2Code], [alpha3Code]) VALUES ('Saint Barthelemy', 'BL', 'BLM');
INSERT INTO [dbo].[ISOcountryCode]([country], [alpha2Code], [alpha3Code]) VALUES ('Bermuda', 'BM', 'BMU');
INSERT INTO [dbo].[ISOcountryCode]([country], [alpha2Code], [alpha3Code]) VALUES ('Brunei', 'BN', 'BRN');
INSERT INTO [dbo].[ISOcountryCode]([country], [alpha2Code], [alpha3Code]) VALUES ('Bolivia', 'BO', 'BOL');
INSERT INTO [dbo].[ISOcountryCode]([country], [alpha2Code], [alpha3Code]) VALUES ('Bonaire, Saint Eustatius and Saba ', 'BQ', 'BES');
INSERT INTO [dbo].[ISOcountryCode]([country], [alpha2Code], [alpha3Code]) VALUES ('Brazil', 'BR', 'BRA');
INSERT INTO [dbo].[ISOcountryCode]([country], [alpha2Code], [alpha3Code]) VALUES ('Bahamas', 'BS', 'BHS');
INSERT INTO [dbo].[ISOcountryCode]([country], [alpha2Code], [alpha3Code]) VALUES ('Bhutan', 'BT', 'BTN');
INSERT INTO [dbo].[ISOcountryCode]([country], [alpha2Code], [alpha3Code]) VALUES ('Bouvet Island', 'BV', 'BVT');
INSERT INTO [dbo].[ISOcountryCode]([country], [alpha2Code], [alpha3Code]) VALUES ('Botswana', 'BW', 'BWA');
INSERT INTO [dbo].[ISOcountryCode]([country], [alpha2Code], [alpha3Code]) VALUES ('Belarus', 'BY', 'BLR');
INSERT INTO [dbo].[ISOcountryCode]([country], [alpha2Code], [alpha3Code]) VALUES ('Belize', 'BZ', 'BLZ');
INSERT INTO [dbo].[ISOcountryCode]([country], [alpha2Code], [alpha3Code]) VALUES ('Canada', 'CA', 'CAN');
INSERT INTO [dbo].[ISOcountryCode]([country], [alpha2Code], [alpha3Code]) VALUES ('Cocos Islands', 'CC', 'CCK');
INSERT INTO [dbo].[ISOcountryCode]([country], [alpha2Code], [alpha3Code]) VALUES ('Democratic Republic of the Congo', 'CD', 'COD');
INSERT INTO [dbo].[ISOcountryCode]([country], [alpha2Code], [alpha3Code]) VALUES ('Central African Republic', 'CF', 'CAF');
INSERT INTO [dbo].[ISOcountryCode]([country], [alpha2Code], [alpha3Code]) VALUES ('Republic of the Congo', 'CG', 'COG');
INSERT INTO [dbo].[ISOcountryCode]([country], [alpha2Code], [alpha3Code]) VALUES ('Switzerland', 'CH', 'CHE');
INSERT INTO [dbo].[ISOcountryCode]([country], [alpha2Code], [alpha3Code]) VALUES ('Ivory Coast', 'CI', 'CIV');
INSERT INTO [dbo].[ISOcountryCode]([country], [alpha2Code], [alpha3Code]) VALUES ('Cook Islands', 'CK', 'COK');
INSERT INTO [dbo].[ISOcountryCode]([country], [alpha2Code], [alpha3Code]) VALUES ('Chile', 'CL', 'CHL');
INSERT INTO [dbo].[ISOcountryCode]([country], [alpha2Code], [alpha3Code]) VALUES ('Cameroon', 'CM', 'CMR');
INSERT INTO [dbo].[ISOcountryCode]([country], [alpha2Code], [alpha3Code]) VALUES ('China', 'CN', 'CHN');
INSERT INTO [dbo].[ISOcountryCode]([country], [alpha2Code], [alpha3Code]) VALUES ('Colombia', 'CO', 'COL');
INSERT INTO [dbo].[ISOcountryCode]([country], [alpha2Code], [alpha3Code]) VALUES ('Costa Rica', 'CR', 'CRI');
INSERT INTO [dbo].[ISOcountryCode]([country], [alpha2Code], [alpha3Code]) VALUES ('Cuba', 'CU', 'CUB');
INSERT INTO [dbo].[ISOcountryCode]([country], [alpha2Code], [alpha3Code]) VALUES ('Cabo Verde', 'CV', 'CPV');
INSERT INTO [dbo].[ISOcountryCode]([country], [alpha2Code], [alpha3Code]) VALUES ('Curacao', 'CW', 'CUW');
INSERT INTO [dbo].[ISOcountryCode]([country], [alpha2Code], [alpha3Code]) VALUES ('Christmas Island', 'CX', 'CXR');
INSERT INTO [dbo].[ISOcountryCode]([country], [alpha2Code], [alpha3Code]) VALUES ('Cyprus', 'CY', 'CYP');
INSERT INTO [dbo].[ISOcountryCode]([country], [alpha2Code], [alpha3Code]) VALUES ('Czechia', 'CZ', 'CZE');
INSERT INTO [dbo].[ISOcountryCode]([country], [alpha2Code], [alpha3Code]) VALUES ('Germany', 'DE', 'DEU');
INSERT INTO [dbo].[ISOcountryCode]([country], [alpha2Code], [alpha3Code]) VALUES ('Djibouti', 'DJ', 'DJI');
INSERT INTO [dbo].[ISOcountryCode]([country], [alpha2Code], [alpha3Code]) VALUES ('Denmark', 'DK', 'DNK');
INSERT INTO [dbo].[ISOcountryCode]([country], [alpha2Code], [alpha3Code]) VALUES ('Dominica', 'DM', 'DMA');
INSERT INTO [dbo].[ISOcountryCode]([country], [alpha2Code], [alpha3Code]) VALUES ('Dominican Republic', 'DO', 'DOM');
INSERT INTO [dbo].[ISOcountryCode]([country], [alpha2Code], [alpha3Code]) VALUES ('Algeria', 'DZ', 'DZA');
INSERT INTO [dbo].[ISOcountryCode]([country], [alpha2Code], [alpha3Code]) VALUES ('Ecuador', 'EC', 'ECU');
INSERT INTO [dbo].[ISOcountryCode]([country], [alpha2Code], [alpha3Code]) VALUES ('Estonia', 'EE', 'EST');
INSERT INTO [dbo].[ISOcountryCode]([country], [alpha2Code], [alpha3Code]) VALUES ('Egypt', 'EG', 'EGY');
INSERT INTO [dbo].[ISOcountryCode]([country], [alpha2Code], [alpha3Code]) VALUES ('Western Sahara', 'EH', 'ESH');
INSERT INTO [dbo].[ISOcountryCode]([country], [alpha2Code], [alpha3Code]) VALUES ('Eritrea', 'ER', 'ERI');
INSERT INTO [dbo].[ISOcountryCode]([country], [alpha2Code], [alpha3Code]) VALUES ('Spain', 'ES', 'ESP');
INSERT INTO [dbo].[ISOcountryCode]([country], [alpha2Code], [alpha3Code]) VALUES ('Ethiopia', 'ET', 'ETH');
INSERT INTO [dbo].[ISOcountryCode]([country], [alpha2Code], [alpha3Code]) VALUES ('Finland', 'FI', 'FIN');
INSERT INTO [dbo].[ISOcountryCode]([country], [alpha2Code], [alpha3Code]) VALUES ('Fiji', 'FJ', 'FJI');
INSERT INTO [dbo].[ISOcountryCode]([country], [alpha2Code], [alpha3Code]) VALUES ('Falkland Islands', 'FK', 'FLK');
INSERT INTO [dbo].[ISOcountryCode]([country], [alpha2Code], [alpha3Code]) VALUES ('Micronesia', 'FM', 'FSM');
INSERT INTO [dbo].[ISOcountryCode]([country], [alpha2Code], [alpha3Code]) VALUES ('Faroe Islands', 'FO', 'FRO');
INSERT INTO [dbo].[ISOcountryCode]([country], [alpha2Code], [alpha3Code]) VALUES ('France', 'FR', 'FRA');
INSERT INTO [dbo].[ISOcountryCode]([country], [alpha2Code], [alpha3Code]) VALUES ('Gabon', 'GA', 'GAB');
INSERT INTO [dbo].[ISOcountryCode]([country], [alpha2Code], [alpha3Code]) VALUES ('United Kingdom', 'GB', 'GBR');
INSERT INTO [dbo].[ISOcountryCode]([country], [alpha2Code], [alpha3Code]) VALUES ('Grenada', 'GD', 'GRD');
INSERT INTO [dbo].[ISOcountryCode]([country], [alpha2Code], [alpha3Code]) VALUES ('Georgia', 'GE', 'GEO');
INSERT INTO [dbo].[ISOcountryCode]([country], [alpha2Code], [alpha3Code]) VALUES ('French Guiana', 'GF', 'GUF');
INSERT INTO [dbo].[ISOcountryCode]([country], [alpha2Code], [alpha3Code]) VALUES ('Guernsey', 'GG', 'GGY');
INSERT INTO [dbo].[ISOcountryCode]([country], [alpha2Code], [alpha3Code]) VALUES ('Ghana', 'GH', 'GHA');
INSERT INTO [dbo].[ISOcountryCode]([country], [alpha2Code], [alpha3Code]) VALUES ('Gibraltar', 'GI', 'GIB');
INSERT INTO [dbo].[ISOcountryCode]([country], [alpha2Code], [alpha3Code]) VALUES ('Greenland', 'GL', 'GRL');
INSERT INTO [dbo].[ISOcountryCode]([country], [alpha2Code], [alpha3Code]) VALUES ('Gambia', 'GM', 'GMB');
INSERT INTO [dbo].[ISOcountryCode]([country], [alpha2Code], [alpha3Code]) VALUES ('Guinea', 'GN', 'GIN');
INSERT INTO [dbo].[ISOcountryCode]([country], [alpha2Code], [alpha3Code]) VALUES ('Guadeloupe', 'GP', 'GLP');
INSERT INTO [dbo].[ISOcountryCode]([country], [alpha2Code], [alpha3Code]) VALUES ('Equatorial Guinea', 'GQ', 'GNQ');
INSERT INTO [dbo].[ISOcountryCode]([country], [alpha2Code], [alpha3Code]) VALUES ('Greece', 'GR', 'GRC');
INSERT INTO [dbo].[ISOcountryCode]([country], [alpha2Code], [alpha3Code]) VALUES ('South Georgia and the South Sandwich Islands', 'GS', 'SGS');
INSERT INTO [dbo].[ISOcountryCode]([country], [alpha2Code], [alpha3Code]) VALUES ('Guatemala', 'GT', 'GTM');
INSERT INTO [dbo].[ISOcountryCode]([country], [alpha2Code], [alpha3Code]) VALUES ('Guam', 'GU', 'GUM');
INSERT INTO [dbo].[ISOcountryCode]([country], [alpha2Code], [alpha3Code]) VALUES ('Guinea-Bissau', 'GW', 'GNB');
INSERT INTO [dbo].[ISOcountryCode]([country], [alpha2Code], [alpha3Code]) VALUES ('Guyana', 'GY', 'GUY');
INSERT INTO [dbo].[ISOcountryCode]([country], [alpha2Code], [alpha3Code]) VALUES ('Hong Kong', 'HK', 'HKG');
INSERT INTO [dbo].[ISOcountryCode]([country], [alpha2Code], [alpha3Code]) VALUES ('Heard Island and McDonald Islands', 'HM', 'HMD');
INSERT INTO [dbo].[ISOcountryCode]([country], [alpha2Code], [alpha3Code]) VALUES ('Honduras', 'HN', 'HND');
INSERT INTO [dbo].[ISOcountryCode]([country], [alpha2Code], [alpha3Code]) VALUES ('Croatia', 'HR', 'HRV');
INSERT INTO [dbo].[ISOcountryCode]([country], [alpha2Code], [alpha3Code]) VALUES ('Haiti', 'HT', 'HTI');
INSERT INTO [dbo].[ISOcountryCode]([country], [alpha2Code], [alpha3Code]) VALUES ('Hungary', 'HU', 'HUN');
INSERT INTO [dbo].[ISOcountryCode]([country], [alpha2Code], [alpha3Code]) VALUES ('Indonesia', 'ID', 'IDN');
INSERT INTO [dbo].[ISOcountryCode]([country], [alpha2Code], [alpha3Code]) VALUES ('Ireland', 'IE', 'IRL');
INSERT INTO [dbo].[ISOcountryCode]([country], [alpha2Code], [alpha3Code]) VALUES ('Israel', 'IL', 'ISR');
INSERT INTO [dbo].[ISOcountryCode]([country], [alpha2Code], [alpha3Code]) VALUES ('Isle of Man', 'IM', 'IMN');
INSERT INTO [dbo].[ISOcountryCode]([country], [alpha2Code], [alpha3Code]) VALUES ('India', 'IN', 'IND');
INSERT INTO [dbo].[ISOcountryCode]([country], [alpha2Code], [alpha3Code]) VALUES ('British Indian Ocean Territory', 'IO', 'IOT');
INSERT INTO [dbo].[ISOcountryCode]([country], [alpha2Code], [alpha3Code]) VALUES ('Iraq', 'IQ', 'IRQ');
INSERT INTO [dbo].[ISOcountryCode]([country], [alpha2Code], [alpha3Code]) VALUES ('Iran', 'IR', 'IRN');
INSERT INTO [dbo].[ISOcountryCode]([country], [alpha2Code], [alpha3Code]) VALUES ('Iceland', 'IS', 'ISL');
INSERT INTO [dbo].[ISOcountryCode]([country], [alpha2Code], [alpha3Code]) VALUES ('Italy', 'IT', 'ITA');
INSERT INTO [dbo].[ISOcountryCode]([country], [alpha2Code], [alpha3Code]) VALUES ('Jersey', 'JE', 'JEY');
INSERT INTO [dbo].[ISOcountryCode]([country], [alpha2Code], [alpha3Code]) VALUES ('Jamaica', 'JM', 'JAM');
INSERT INTO [dbo].[ISOcountryCode]([country], [alpha2Code], [alpha3Code]) VALUES ('Jordan', 'JO', 'JOR');
INSERT INTO [dbo].[ISOcountryCode]([country], [alpha2Code], [alpha3Code]) VALUES ('Japan', 'JP', 'JPN');
INSERT INTO [dbo].[ISOcountryCode]([country], [alpha2Code], [alpha3Code]) VALUES ('Kenya', 'KE', 'KEN');
INSERT INTO [dbo].[ISOcountryCode]([country], [alpha2Code], [alpha3Code]) VALUES ('Kyrgyzstan', 'KG', 'KGZ');
INSERT INTO [dbo].[ISOcountryCode]([country], [alpha2Code], [alpha3Code]) VALUES ('Cambodia', 'KH', 'KHM');
INSERT INTO [dbo].[ISOcountryCode]([country], [alpha2Code], [alpha3Code]) VALUES ('Kiribati', 'KI', 'KIR');
INSERT INTO [dbo].[ISOcountryCode]([country], [alpha2Code], [alpha3Code]) VALUES ('Comoros', 'KM', 'COM');
INSERT INTO [dbo].[ISOcountryCode]([country], [alpha2Code], [alpha3Code]) VALUES ('Saint Kitts and Nevis', 'KN', 'KNA');
INSERT INTO [dbo].[ISOcountryCode]([country], [alpha2Code], [alpha3Code]) VALUES ('North Korea', 'KP', 'PRK');
INSERT INTO [dbo].[ISOcountryCode]([country], [alpha2Code], [alpha3Code]) VALUES ('South Korea', 'KR', 'KOR');
INSERT INTO [dbo].[ISOcountryCode]([country], [alpha2Code], [alpha3Code]) VALUES ('Kosovo', 'XK', 'XKX');
INSERT INTO [dbo].[ISOcountryCode]([country], [alpha2Code], [alpha3Code]) VALUES ('Kuwait', 'KW', 'KWT');
INSERT INTO [dbo].[ISOcountryCode]([country], [alpha2Code], [alpha3Code]) VALUES ('Cayman Islands', 'KY', 'CYM');
INSERT INTO [dbo].[ISOcountryCode]([country], [alpha2Code], [alpha3Code]) VALUES ('Kazakhstan', 'KZ', 'KAZ');
INSERT INTO [dbo].[ISOcountryCode]([country], [alpha2Code], [alpha3Code]) VALUES ('Laos', 'LA', 'LAO');
INSERT INTO [dbo].[ISOcountryCode]([country], [alpha2Code], [alpha3Code]) VALUES ('Lebanon', 'LB', 'LBN');
INSERT INTO [dbo].[ISOcountryCode]([country], [alpha2Code], [alpha3Code]) VALUES ('Saint Lucia', 'LC', 'LCA');
INSERT INTO [dbo].[ISOcountryCode]([country], [alpha2Code], [alpha3Code]) VALUES ('Liechtenstein', 'LI', 'LIE');
INSERT INTO [dbo].[ISOcountryCode]([country], [alpha2Code], [alpha3Code]) VALUES ('Sri Lanka', 'LK', 'LKA');
INSERT INTO [dbo].[ISOcountryCode]([country], [alpha2Code], [alpha3Code]) VALUES ('Liberia', 'LR', 'LBR');
INSERT INTO [dbo].[ISOcountryCode]([country], [alpha2Code], [alpha3Code]) VALUES ('Lesotho', 'LS', 'LSO');
INSERT INTO [dbo].[ISOcountryCode]([country], [alpha2Code], [alpha3Code]) VALUES ('Lithuania', 'LT', 'LTU');
INSERT INTO [dbo].[ISOcountryCode]([country], [alpha2Code], [alpha3Code]) VALUES ('Luxembourg', 'LU', 'LUX');
INSERT INTO [dbo].[ISOcountryCode]([country], [alpha2Code], [alpha3Code]) VALUES ('Latvia', 'LV', 'LVA');
INSERT INTO [dbo].[ISOcountryCode]([country], [alpha2Code], [alpha3Code]) VALUES ('Libya', 'LY', 'LBY');
INSERT INTO [dbo].[ISOcountryCode]([country], [alpha2Code], [alpha3Code]) VALUES ('Morocco', 'MA', 'MAR');
INSERT INTO [dbo].[ISOcountryCode]([country], [alpha2Code], [alpha3Code]) VALUES ('Monaco', 'MC', 'MCO');
INSERT INTO [dbo].[ISOcountryCode]([country], [alpha2Code], [alpha3Code]) VALUES ('Moldova', 'MD', 'MDA');
INSERT INTO [dbo].[ISOcountryCode]([country], [alpha2Code], [alpha3Code]) VALUES ('Montenegro', 'ME', 'MNE');
INSERT INTO [dbo].[ISOcountryCode]([country], [alpha2Code], [alpha3Code]) VALUES ('Saint Martin', 'MF', 'MAF');
INSERT INTO [dbo].[ISOcountryCode]([country], [alpha2Code], [alpha3Code]) VALUES ('Madagascar', 'MG', 'MDG');
INSERT INTO [dbo].[ISOcountryCode]([country], [alpha2Code], [alpha3Code]) VALUES ('Marshall Islands', 'MH', 'MHL');
INSERT INTO [dbo].[ISOcountryCode]([country], [alpha2Code], [alpha3Code]) VALUES ('North Macedonia', 'MK', 'MKD');
INSERT INTO [dbo].[ISOcountryCode]([country], [alpha2Code], [alpha3Code]) VALUES ('Mali', 'ML', 'MLI');
INSERT INTO [dbo].[ISOcountryCode]([country], [alpha2Code], [alpha3Code]) VALUES ('Myanmar', 'MM', 'MMR');
INSERT INTO [dbo].[ISOcountryCode]([country], [alpha2Code], [alpha3Code]) VALUES ('Mongolia', 'MN', 'MNG');
INSERT INTO [dbo].[ISOcountryCode]([country], [alpha2Code], [alpha3Code]) VALUES ('Macao', 'MO', 'MAC');
INSERT INTO [dbo].[ISOcountryCode]([country], [alpha2Code], [alpha3Code]) VALUES ('Northern Mariana Islands', 'MP', 'MNP');
INSERT INTO [dbo].[ISOcountryCode]([country], [alpha2Code], [alpha3Code]) VALUES ('Martinique', 'MQ', 'MTQ');
INSERT INTO [dbo].[ISOcountryCode]([country], [alpha2Code], [alpha3Code]) VALUES ('Mauritania', 'MR', 'MRT');
INSERT INTO [dbo].[ISOcountryCode]([country], [alpha2Code], [alpha3Code]) VALUES ('Montserrat', 'MS', 'MSR');
INSERT INTO [dbo].[ISOcountryCode]([country], [alpha2Code], [alpha3Code]) VALUES ('Malta', 'MT', 'MLT');
INSERT INTO [dbo].[ISOcountryCode]([country], [alpha2Code], [alpha3Code]) VALUES ('Mauritius', 'MU', 'MUS');
INSERT INTO [dbo].[ISOcountryCode]([country], [alpha2Code], [alpha3Code]) VALUES ('Maldives', 'MV', 'MDV');
INSERT INTO [dbo].[ISOcountryCode]([country], [alpha2Code], [alpha3Code]) VALUES ('Malawi', 'MW', 'MWI');
INSERT INTO [dbo].[ISOcountryCode]([country], [alpha2Code], [alpha3Code]) VALUES ('Mexico', 'MX', 'MEX');
INSERT INTO [dbo].[ISOcountryCode]([country], [alpha2Code], [alpha3Code]) VALUES ('Malaysia', 'MY', 'MYS');
INSERT INTO [dbo].[ISOcountryCode]([country], [alpha2Code], [alpha3Code]) VALUES ('Mozambique', 'MZ', 'MOZ');
INSERT INTO [dbo].[ISOcountryCode]([country], [alpha2Code], [alpha3Code]) VALUES ('Namibia', 'NA', 'NAM');
INSERT INTO [dbo].[ISOcountryCode]([country], [alpha2Code], [alpha3Code]) VALUES ('New Caledonia', 'NC', 'NCL');
INSERT INTO [dbo].[ISOcountryCode]([country], [alpha2Code], [alpha3Code]) VALUES ('Niger', 'NE', 'NER');
INSERT INTO [dbo].[ISOcountryCode]([country], [alpha2Code], [alpha3Code]) VALUES ('Norfolk Island', 'NF', 'NFK');
INSERT INTO [dbo].[ISOcountryCode]([country], [alpha2Code], [alpha3Code]) VALUES ('Nigeria', 'NG', 'NGA');
INSERT INTO [dbo].[ISOcountryCode]([country], [alpha2Code], [alpha3Code]) VALUES ('Nicaragua', 'NI', 'NIC');
INSERT INTO [dbo].[ISOcountryCode]([country], [alpha2Code], [alpha3Code]) VALUES ('Netherlands', 'NL', 'NLD');
INSERT INTO [dbo].[ISOcountryCode]([country], [alpha2Code], [alpha3Code]) VALUES ('Norway', 'NO', 'NOR');
INSERT INTO [dbo].[ISOcountryCode]([country], [alpha2Code], [alpha3Code]) VALUES ('Nepal', 'NP', 'NPL');
INSERT INTO [dbo].[ISOcountryCode]([country], [alpha2Code], [alpha3Code]) VALUES ('Nauru', 'NR', 'NRU');
INSERT INTO [dbo].[ISOcountryCode]([country], [alpha2Code], [alpha3Code]) VALUES ('Niue', 'NU', 'NIU');
INSERT INTO [dbo].[ISOcountryCode]([country], [alpha2Code], [alpha3Code]) VALUES ('New Zealand', 'NZ', 'NZL');
INSERT INTO [dbo].[ISOcountryCode]([country], [alpha2Code], [alpha3Code]) VALUES ('Oman', 'OM', 'OMN');
INSERT INTO [dbo].[ISOcountryCode]([country], [alpha2Code], [alpha3Code]) VALUES ('Panama', 'PA', 'PAN');
INSERT INTO [dbo].[ISOcountryCode]([country], [alpha2Code], [alpha3Code]) VALUES ('Peru', 'PE', 'PER');
INSERT INTO [dbo].[ISOcountryCode]([country], [alpha2Code], [alpha3Code]) VALUES ('French Polynesia', 'PF', 'PYF');
INSERT INTO [dbo].[ISOcountryCode]([country], [alpha2Code], [alpha3Code]) VALUES ('Papua New Guinea', 'PG', 'PNG');
INSERT INTO [dbo].[ISOcountryCode]([country], [alpha2Code], [alpha3Code]) VALUES ('Philippines', 'PH', 'PHL');
INSERT INTO [dbo].[ISOcountryCode]([country], [alpha2Code], [alpha3Code]) VALUES ('Pakistan', 'PK', 'PAK');
INSERT INTO [dbo].[ISOcountryCode]([country], [alpha2Code], [alpha3Code]) VALUES ('Poland', 'PL', 'POL');
INSERT INTO [dbo].[ISOcountryCode]([country], [alpha2Code], [alpha3Code]) VALUES ('Saint Pierre and Miquelon', 'PM', 'SPM');
INSERT INTO [dbo].[ISOcountryCode]([country], [alpha2Code], [alpha3Code]) VALUES ('Pitcairn', 'PN', 'PCN');
INSERT INTO [dbo].[ISOcountryCode]([country], [alpha2Code], [alpha3Code]) VALUES ('Puerto Rico', 'PR', 'PRI');
INSERT INTO [dbo].[ISOcountryCode]([country], [alpha2Code], [alpha3Code]) VALUES ('Palestinian Territory', 'PS', 'PSE');
INSERT INTO [dbo].[ISOcountryCode]([country], [alpha2Code], [alpha3Code]) VALUES ('Portugal', 'PT', 'PRT');
INSERT INTO [dbo].[ISOcountryCode]([country], [alpha2Code], [alpha3Code]) VALUES ('Palau', 'PW', 'PLW');
INSERT INTO [dbo].[ISOcountryCode]([country], [alpha2Code], [alpha3Code]) VALUES ('Paraguay', 'PY', 'PRY');
INSERT INTO [dbo].[ISOcountryCode]([country], [alpha2Code], [alpha3Code]) VALUES ('Qatar', 'QA', 'QAT');
INSERT INTO [dbo].[ISOcountryCode]([country], [alpha2Code], [alpha3Code]) VALUES ('Reunion', 'RE', 'REU');
INSERT INTO [dbo].[ISOcountryCode]([country], [alpha2Code], [alpha3Code]) VALUES ('Romania', 'RO', 'ROU');
INSERT INTO [dbo].[ISOcountryCode]([country], [alpha2Code], [alpha3Code]) VALUES ('Serbia', 'RS', 'SRB');
INSERT INTO [dbo].[ISOcountryCode]([country], [alpha2Code], [alpha3Code]) VALUES ('Russia', 'RU', 'RUS');
INSERT INTO [dbo].[ISOcountryCode]([country], [alpha2Code], [alpha3Code]) VALUES ('Rwanda', 'RW', 'RWA');
INSERT INTO [dbo].[ISOcountryCode]([country], [alpha2Code], [alpha3Code]) VALUES ('Saudi Arabia', 'SA', 'SAU');
INSERT INTO [dbo].[ISOcountryCode]([country], [alpha2Code], [alpha3Code]) VALUES ('Solomon Islands', 'SB', 'SLB');
INSERT INTO [dbo].[ISOcountryCode]([country], [alpha2Code], [alpha3Code]) VALUES ('Seychelles', 'SC', 'SYC');
INSERT INTO [dbo].[ISOcountryCode]([country], [alpha2Code], [alpha3Code]) VALUES ('Sudan', 'SD', 'SDN');
INSERT INTO [dbo].[ISOcountryCode]([country], [alpha2Code], [alpha3Code]) VALUES ('South Sudan', 'SS', 'SSD');
INSERT INTO [dbo].[ISOcountryCode]([country], [alpha2Code], [alpha3Code]) VALUES ('Sweden', 'SE', 'SWE');
INSERT INTO [dbo].[ISOcountryCode]([country], [alpha2Code], [alpha3Code]) VALUES ('Singapore', 'SG', 'SGP');
INSERT INTO [dbo].[ISOcountryCode]([country], [alpha2Code], [alpha3Code]) VALUES ('Saint Helena', 'SH', 'SHN');
INSERT INTO [dbo].[ISOcountryCode]([country], [alpha2Code], [alpha3Code]) VALUES ('Slovenia', 'SI', 'SVN');
INSERT INTO [dbo].[ISOcountryCode]([country], [alpha2Code], [alpha3Code]) VALUES ('Svalbard and Jan Mayen', 'SJ', 'SJM');
INSERT INTO [dbo].[ISOcountryCode]([country], [alpha2Code], [alpha3Code]) VALUES ('Slovakia', 'SK', 'SVK');
INSERT INTO [dbo].[ISOcountryCode]([country], [alpha2Code], [alpha3Code]) VALUES ('Sierra Leone', 'SL', 'SLE');
INSERT INTO [dbo].[ISOcountryCode]([country], [alpha2Code], [alpha3Code]) VALUES ('San Marino', 'SM', 'SMR');
INSERT INTO [dbo].[ISOcountryCode]([country], [alpha2Code], [alpha3Code]) VALUES ('Senegal', 'SN', 'SEN');
INSERT INTO [dbo].[ISOcountryCode]([country], [alpha2Code], [alpha3Code]) VALUES ('Somalia', 'SO', 'SOM');
INSERT INTO [dbo].[ISOcountryCode]([country], [alpha2Code], [alpha3Code]) VALUES ('Suriname', 'SR', 'SUR');
INSERT INTO [dbo].[ISOcountryCode]([country], [alpha2Code], [alpha3Code]) VALUES ('Sao Tome and Principe', 'ST', 'STP');
INSERT INTO [dbo].[ISOcountryCode]([country], [alpha2Code], [alpha3Code]) VALUES ('El Salvador', 'SV', 'SLV');
INSERT INTO [dbo].[ISOcountryCode]([country], [alpha2Code], [alpha3Code]) VALUES ('Sint Maarten', 'SX', 'SXM');
INSERT INTO [dbo].[ISOcountryCode]([country], [alpha2Code], [alpha3Code]) VALUES ('Syria', 'SY', 'SYR');
INSERT INTO [dbo].[ISOcountryCode]([country], [alpha2Code], [alpha3Code]) VALUES ('Eswatini', 'SZ', 'SWZ');
INSERT INTO [dbo].[ISOcountryCode]([country], [alpha2Code], [alpha3Code]) VALUES ('Turks and Caicos Islands', 'TC', 'TCA');
INSERT INTO [dbo].[ISOcountryCode]([country], [alpha2Code], [alpha3Code]) VALUES ('Chad', 'TD', 'TCD');
INSERT INTO [dbo].[ISOcountryCode]([country], [alpha2Code], [alpha3Code]) VALUES ('French Southern Territories', 'TF', 'ATF');
INSERT INTO [dbo].[ISOcountryCode]([country], [alpha2Code], [alpha3Code]) VALUES ('Togo', 'TG', 'TGO');
INSERT INTO [dbo].[ISOcountryCode]([country], [alpha2Code], [alpha3Code]) VALUES ('Thailand', 'TH', 'THA');
INSERT INTO [dbo].[ISOcountryCode]([country], [alpha2Code], [alpha3Code]) VALUES ('Tajikistan', 'TJ', 'TJK');
INSERT INTO [dbo].[ISOcountryCode]([country], [alpha2Code], [alpha3Code]) VALUES ('Tokelau', 'TK', 'TKL');
INSERT INTO [dbo].[ISOcountryCode]([country], [alpha2Code], [alpha3Code]) VALUES ('Timor Leste', 'TL', 'TLS');
INSERT INTO [dbo].[ISOcountryCode]([country], [alpha2Code], [alpha3Code]) VALUES ('Turkmenistan', 'TM', 'TKM');
INSERT INTO [dbo].[ISOcountryCode]([country], [alpha2Code], [alpha3Code]) VALUES ('Tunisia', 'TN', 'TUN');
INSERT INTO [dbo].[ISOcountryCode]([country], [alpha2Code], [alpha3Code]) VALUES ('Tonga', 'TO', 'TON');
INSERT INTO [dbo].[ISOcountryCode]([country], [alpha2Code], [alpha3Code]) VALUES ('Turkey', 'TR', 'TUR');
INSERT INTO [dbo].[ISOcountryCode]([country], [alpha2Code], [alpha3Code]) VALUES ('Trinidad and Tobago', 'TT', 'TTO');
INSERT INTO [dbo].[ISOcountryCode]([country], [alpha2Code], [alpha3Code]) VALUES ('Tuvalu', 'TV', 'TUV');
INSERT INTO [dbo].[ISOcountryCode]([country], [alpha2Code], [alpha3Code]) VALUES ('Taiwan', 'TW', 'TWN');
INSERT INTO [dbo].[ISOcountryCode]([country], [alpha2Code], [alpha3Code]) VALUES ('Tanzania', 'TZ', 'TZA');
INSERT INTO [dbo].[ISOcountryCode]([country], [alpha2Code], [alpha3Code]) VALUES ('Ukraine', 'UA', 'UKR');
INSERT INTO [dbo].[ISOcountryCode]([country], [alpha2Code], [alpha3Code]) VALUES ('Uganda', 'UG', 'UGA');
INSERT INTO [dbo].[ISOcountryCode]([country], [alpha2Code], [alpha3Code]) VALUES ('United States Minor Outlying Islands', 'UM', 'UMI');
INSERT INTO [dbo].[ISOcountryCode]([country], [alpha2Code], [alpha3Code]) VALUES ('United States', 'US', 'USA');
INSERT INTO [dbo].[ISOcountryCode]([country], [alpha2Code], [alpha3Code]) VALUES ('Uruguay', 'UY', 'URY');
INSERT INTO [dbo].[ISOcountryCode]([country], [alpha2Code], [alpha3Code]) VALUES ('Uzbekistan', 'UZ', 'UZB');
INSERT INTO [dbo].[ISOcountryCode]([country], [alpha2Code], [alpha3Code]) VALUES ('Vatican', 'VA', 'VAT');
INSERT INTO [dbo].[ISOcountryCode]([country], [alpha2Code], [alpha3Code]) VALUES ('Saint Vincent and the Grenadines', 'VC', 'VCT');
INSERT INTO [dbo].[ISOcountryCode]([country], [alpha2Code], [alpha3Code]) VALUES ('Venezuela', 'VE', 'VEN');
INSERT INTO [dbo].[ISOcountryCode]([country], [alpha2Code], [alpha3Code]) VALUES ('British Virgin Islands', 'VG', 'VGB');
INSERT INTO [dbo].[ISOcountryCode]([country], [alpha2Code], [alpha3Code]) VALUES ('U.S. Virgin Islands', 'VI', 'VIR');
INSERT INTO [dbo].[ISOcountryCode]([country], [alpha2Code], [alpha3Code]) VALUES ('Vietnam', 'VN', 'VNM');
INSERT INTO [dbo].[ISOcountryCode]([country], [alpha2Code], [alpha3Code]) VALUES ('Vanuatu', 'VU', 'VUT');
INSERT INTO [dbo].[ISOcountryCode]([country], [alpha2Code], [alpha3Code]) VALUES ('Wallis and Futuna', 'WF', 'WLF');
INSERT INTO [dbo].[ISOcountryCode]([country], [alpha2Code], [alpha3Code]) VALUES ('Samoa', 'WS', 'WSM');
INSERT INTO [dbo].[ISOcountryCode]([country], [alpha2Code], [alpha3Code]) VALUES ('Yemen', 'YE', 'YEM');
INSERT INTO [dbo].[ISOcountryCode]([country], [alpha2Code], [alpha3Code]) VALUES ('Mayotte', 'YT', 'MYT');
INSERT INTO [dbo].[ISOcountryCode]([country], [alpha2Code], [alpha3Code]) VALUES ('South Africa', 'ZA', 'ZAF');
INSERT INTO [dbo].[ISOcountryCode]([country], [alpha2Code], [alpha3Code]) VALUES ('Zambia', 'ZM', 'ZMB');
INSERT INTO [dbo].[ISOcountryCode]([country], [alpha2Code], [alpha3Code]) VALUES ('Zimbabwe', 'ZW', 'ZWE');
INSERT INTO [dbo].[ISOcountryCode]([country], [alpha2Code], [alpha3Code]) VALUES ('Serbia and Montenegro', 'CS', 'SCG');
INSERT INTO [dbo].[ISOcountryCode]([country], [alpha2Code], [alpha3Code]) VALUES ('Netherlands Antilles', 'AN', 'ANT');
